package org.openublpe.xmlbuilder.rules.files.standard.invoice;

import org.openublpe.xmlbuilder.core.models.inputoutput.DocumentInputOutputModel;
import org.openublpe.xmlbuilder.core.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.core.models.input.standard.invoice.InvoiceInputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.invoice.InvoiceOutputModel;
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog1;
import org.openublpe.xmlbuilder.rules.utils.UBLUtils;

dialect "java"

rule "Codigo tipo comprobante - Factura/Boleta"
when
    $inputOutput : DocumentInputOutputModel(
        input instanceof InvoiceInputModel,
        output instanceof InvoiceOutputModel,
        $input: input,
        $output: output
    )
then
    InvoiceInputModel invoiceInput = (InvoiceInputModel) $input;
    InvoiceOutputModel invoiceOutput = (InvoiceOutputModel) $output;

    if (UBLUtils.FACTURA_SERIE_REGEX.matcher(invoiceInput.getSerie()).find()) {
        invoiceOutput.setTipoInvoice(Catalog1.FACTURA);
    } else if (UBLUtils.BOLETA_SERIE_REGEX.matcher(invoiceInput.getSerie()).find()) {
       invoiceOutput.setTipoInvoice(Catalog1.BOLETA);
    }
end
