package org.openublpe.xmlbuilder.rules.files.standard.invoice;

import org.openublpe.xmlbuilder.core.models.inputoutput.DocumentInputOutputModel;
import org.openublpe.xmlbuilder.core.models.input.standard.invoice.InvoiceInputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.invoice.InvoiceOutputModel;
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog1;

dialect "java"

declare InvoiceInputOutputModel
    input : InvoiceInputModel
    output : InvoiceOutputModel
end

rule "INVOICE_IO_INIT"
when
    $inputOutput : DocumentInputOutputModel(
        input instanceof InvoiceInputModel,
        output instanceof InvoiceOutputModel,
        $input: input,
        $output: output
    )
then
    InvoiceInputModel invoiceInput = (InvoiceInputModel) $input;
    InvoiceOutputModel invoiceOutput = (InvoiceOutputModel) $output;

    insert(new InvoiceInputOutputModel(invoiceInput, invoiceOutput));
end

rule "INVOICE_IO_TIPO_DOCUMENTO_FACTURA"
when
    $inputOutput : InvoiceInputOutputModel(
        $input: input,
        $output: output,
        $input.serie matches "^[F|f].*$",
        $output.tipoInvoice == null
    )
then
    $output.setTipoInvoice(Catalog1.FACTURA);
end

rule "INVOICE_IO_TIPO_DOCUMENTO_BOLETA"
when
    $inputOutput : InvoiceInputOutputModel(
        $input: input,
        $output: output,
        $input.serie matches "^[B|b].*$",
        $output.tipoInvoice == null
    )
then
    $output.setTipoInvoice(Catalog1.BOLETA);
end
