package rules.note;

import org.openublpe.xmlbuilder.models.input.AbstractNoteInputDocumentModel;
import org.openublpe.xmlbuilder.models.output.AbstractNoteOutputDocumentModel
import java.util.regex.Pattern
import org.openublpe.xmlbuilder.models.ubl.Catalog6
import org.openublpe.xmlbuilder.models.ubl.Catalog1;

dialect "java"

rule "Invoice Reference"
when
    $input : AbstractNoteInputDocumentModel(serieNumeroInvoiceReference != null)
    $output : AbstractNoteOutputDocumentModel()
then
    $output.setSerieNumeroInvoiceReference($input.getSerieNumeroInvoiceReference());
    $output.setDescripcionSustentoInvoiceReference($input.getDescripcionSustentoInvoiceReference());

    if (Pattern.compile("^[F|f].*$").matcher($output.getSerieNumeroInvoiceReference()).find()) {
        $output.setTipoComprobanteInvoiceReference(Catalog1.FACTURA);
    } else if (Pattern.compile("^[B|b].*$").matcher($output.getSerieNumeroInvoiceReference()).find()) {
       $output.setTipoComprobanteInvoiceReference(Catalog1.BOLETA);
    }

end