package org.openublpe.xmlbuilder.rules.files.sunat;

import org.openublpe.xmlbuilder.core.models.input.sunat.SummaryDocumentInputModel;
import org.openublpe.xmlbuilder.core.models.output.sunat.SummaryDocumentOutputModel;
import org.openublpe.xmlbuilder.core.models.input.sunat.SummaryDocumentLineInputModel;
import java.util.ArrayList;
import java.math.BigDecimal
import org.openublpe.xmlbuilder.core.models.input.sunat.SummaryDocumentLineInputModel;

dialect "java"

rule "Summary Detalle"
when
    $input : SummaryDocumentInputModel(detalle != null)
    $output : SummaryDocumentOutputModel()
then
    $output.setDetalle(new ArrayList<>());

    for (SummaryDocumentLineInputModel item : $input.getDetalle()) {
        insert(item);
    }
end
