package org.openublpe.xmlbuilder.rules.files.sunat;

import org.openublpe.xmlbuilder.core.models.input.sunat.SummaryDocumentInputModel;
import org.openublpe.xmlbuilder.core.models.output.sunat.SummaryDocumentOutputModel;
import java.util.Calendar
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog10
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog1
import org.openublpe.xmlbuilder.core.models.output.common.FirmanteOutputModel
import org.openublpe.xmlbuilder.core.models.output.common.ProveedorOutputModel;

import function org.openublpe.xmlbuilder.rules.utils.DateUtils.toGregorianCalendarDate;

global java.lang.String DEFAULT_MONEDA;

dialect "java"

rule "Summary Document"
when
    $input : SummaryDocumentInputModel()
    $output : SummaryDocumentOutputModel()
then
    long fechaEmision = $input.getFechaEmision() != null
            ? $input.getFechaEmision()
            : Calendar.getInstance().getTimeInMillis();
    String fechaEmisionString = toGregorianCalendarDate(fechaEmision);

    $output.setSerieNumero("RC-" + fechaEmisionString.replaceAll("-", "") + "-" + $input.getNumero());
    $output.setFechaEmision(fechaEmisionString);

    $output.setFechaEmisionDocumentReference(toGregorianCalendarDate($input.getFechaEmisionDocumentReference()));

    $output.setMoneda($input.getMoneda() != null ? $input.getMoneda() : DEFAULT_MONEDA);

    FirmanteOutputModel firmante = new FirmanteOutputModel();
    $output.setFirmante(firmante);

    ProveedorOutputModel proveedor = new ProveedorOutputModel();
    $output.setProveedor(proveedor);

    insert($input.getFirmante());
    insert($input.getProveedor());
    insert(firmante);
    insert(proveedor);
end
