package rules.standard.invoice;

import org.openublpe.xmlbuilder.core.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.core.models.input.standard.invoice.InvoiceInputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.invoice.InvoiceOutputModel;
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog1;
import org.openublpe.xmlbuilder.utils.UBLUtils
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog1;

dialect "java"

rule "Codigo tipo comprobante - Factura/Boleta"
when
    $input : InvoiceInputModel(serie != null)
    $output : InvoiceOutputModel()
then
    if (UBLUtils.FACTURA_SERIE_REGEX.matcher($input.getSerie()).find()) {
        $output.setTipoInvoice(Catalog1.FACTURA);
    } else if (UBLUtils.BOLETA_SERIE_REGEX.matcher($input.getSerie()).find()) {
       $output.setTipoInvoice(Catalog1.BOLETA);
    }
end
