## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/centos-quarkus-maven:19.2.1 AS build

COPY api-core /usr/src/app/api-core
COPY api /usr/src/app/api
COPY api-signer /usr/src/app/api-signer
COPY core /usr/src/app/core
COPY extensions /usr/src/app/extensions
COPY input-test-data /usr/src/app/input-test-data
COPY rules /usr/src/app/rules
COPY templates /usr/src/app/templates
COPY ui /usr/src/app/ui
COPY pom.xml /usr/src/app

USER root
RUN chown -R quarkus /usr/src/app
USER quarkus
RUN mvn -f /usr/src/app/pom.xml -P native-api,native-api-signer -Dquarkus.profile=native-test verify
