package org.openublpe.xmlbuilder.rules.files.standard;

import org.openublpe.xmlbuilder.rules.files.standard.ProveedorInputOutputModel;
import org.openublpe.xmlbuilder.core.models.input.common.ContactoInputModel;
import org.openublpe.xmlbuilder.core.models.output.common.ContactoOutputModel;

dialect "java"

declare ContactoInputOutputModel
   input : ContactoInputModel
   output : ContactoOutputModel
end

rule "PROVEEDOR_IO_CONTACTO_INIT"
when
    $inputOutput: ProveedorInputOutputModel(
        $input: input,
        $output: output,
        $input.contacto != null,
        $output.contacto == null
    )
then
    $output.setContacto(new ContactoOutputModel());

    insert(new ContactoInputOutputModel($input.getContacto(), $output.getContacto()));
end

rule "CONTACTO_IO"
when
    $inputOutput: ContactoInputOutputModel(
        $input : input,
        $output : output
    )
then
    $output.setEmail($input.getEmail());
    $output.setTelefono($input.getTelefono());
end
