package org.openublpe.xmlbuilder.rules.files.standard;

import org.openublpe.xmlbuilder.core.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.core.models.input.standard.DetalleInputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.DocumentOutputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.DetalleOutputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.ImpuestoDetalladoIGVOutputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.ImpuestoDetalladoICBOutputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.DetallePrecioReferenciaOutputModel;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.math.RoundingMode;

import org.openublpe.xmlbuilder.core.models.catalogs.Catalog;
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog7;
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog16
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog5;
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog7_1;

import function org.openublpe.xmlbuilder.rules.utils.NumberUtils.format2Digists
import org.openublpe.xmlbuilder.core.models.output.standard.ImpuestoDetalladoICBOutputModel
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog5;

global java.math.BigDecimal IGV;
global java.math.BigDecimal ICB;
global java.lang.String DEFAULT_UNIDAD_MEDIDA;
global org.openublpe.xmlbuilder.core.models.catalogs.Catalog7 DEFAULT_TIPO_IGV;

dialect "java"

rule "Detalle Item"
when
    $input : DocumentInputModel(detalle != null)
    $output : DocumentOutputModel()
    $inputDetalle: DetalleInputModel()
then
    DetalleOutputModel outputDetalle = new DetalleOutputModel();
    $output.getDetalle().add(outputDetalle);

    // Descripcion, unidad de medida
    outputDetalle.setDescripcion($inputDetalle.getDescripcion());
    outputDetalle.setUnidadMedida($inputDetalle.getUnidadMedida() != null ? $inputDetalle.getUnidadMedida() : DEFAULT_UNIDAD_MEDIDA);

    // Cantidad
    BigDecimal cantidad = $inputDetalle.getCantidad();
    outputDetalle.setCantidad(cantidad);

    // Precio unitario
    BigDecimal precioUnitario = $inputDetalle.getPrecioUnitario();
    outputDetalle.setPrecioUnitario(precioUnitario);

    // Tipo IGV
    Catalog7 tipoIgv = $inputDetalle.getTipoIGV() != null
        ? Catalog.valueOfCode(Catalog7.class, $inputDetalle.getTipoIGV()).get()
        : DEFAULT_TIPO_IGV;

    // IGV a usar
    BigDecimal IGV_TO_USE = tipoIgv.getGrupo().equals(Catalog7_1.GRAVADO)
        ? IGV
        : BigDecimal.ZERO;

    BigDecimal igvPorcentual = IGV_TO_USE.multiply(new BigDecimal("100"));
    outputDetalle.setIgvPorcentual(igvPorcentual);

    // Total
    BigDecimal total = format2Digists(cantidad.multiply(precioUnitario));
    outputDetalle.setTotal(total);

    // Subtotal
    BigDecimal subTotal = total.divide(IGV_TO_USE.add(BigDecimal.ONE), 2, RoundingMode.HALF_EVEN);

    // importe igv
    BigDecimal importeIgv = total.subtract(subTotal);


    // IGV
    outputDetalle.setIgv(new ImpuestoDetalladoIGVOutputModel());
    outputDetalle.getIgv().setTipo(tipoIgv);
    outputDetalle.getIgv().setCategoria(tipoIgv.getTaxCategory());
    outputDetalle.getIgv().setBaseImponible(subTotal);
    outputDetalle.getIgv().setImporte(importeIgv);


    // ICB
    outputDetalle.setIcbAplicado(ICB);
    if ($inputDetalle.isIcb()) {
        outputDetalle.setIcb(new ImpuestoDetalladoICBOutputModel());
        BigDecimal importeICB = cantidad.multiply(ICB);
        outputDetalle.getIcb().setImporte(format2Digists(importeICB));
        outputDetalle.getIcb().setCategoria(Catalog5.ICBPER);
    }


    // Precios de referencia
    outputDetalle.setPreciosDeReferencia(new ArrayList<>());

    if (tipoIgv.isOperacionOnerosa()) {
        outputDetalle.setSubtotal(subTotal);

        // Valor unitario
        BigDecimal valorUnitario = subTotal.divide(cantidad, 2, RoundingMode.HALF_EVEN);
        outputDetalle.setValorUnitario(valorUnitario);

        outputDetalle.getPreciosDeReferencia().add(new DetallePrecioReferenciaOutputModel(precioUnitario, Catalog16.PRECIO_UNITARIO_INCLUYE_IGV));
    } else {
        outputDetalle.setSubtotal(total);

        // Valor unitario
        outputDetalle.setValorUnitario(BigDecimal.ZERO);

        outputDetalle.getPreciosDeReferencia().add(new DetallePrecioReferenciaOutputModel(precioUnitario, Catalog16.VALOR_FERENCIAL_UNITARIO_EN_OPERACIONES_NO_ONEROSAS));
    }
end
