package org.openublpe.xmlbuilder.rules.files.standard;

import org.openublpe.xmlbuilder.core.models.inputoutput.DocumentInputOutputModel;
import org.openublpe.xmlbuilder.core.models.input.standard.GuiaRemisionRelacionadaInputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.GuiaRemisionRelacionadaOutputModel;
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog;
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog1;
import java.util.ArrayList;

dialect "java"

declare GuiaRemisionRelacionadaInputOutputModel
   input : GuiaRemisionRelacionadaInputModel
   output : GuiaRemisionRelacionadaOutputModel
end

rule "GUIA_REMISION_RELACIONADA_IO_INIT"
when
    $inputOutput : DocumentInputOutputModel(
        $input : input,
        $input.guiasDeRemisionRelacionadas != null,
        $output : output
    )
then
    $output.setGuiasDeRemisionRelacionadas(new ArrayList<>());
    for (GuiaRemisionRelacionadaInputModel guiaInput : $input.getGuiasDeRemisionRelacionadas()) {
        GuiaRemisionRelacionadaOutputModel guiaOutput = new GuiaRemisionRelacionadaOutputModel();
        $output.getGuiasDeRemisionRelacionadas().add(guiaOutput);

        insert(new GuiaRemisionRelacionadaInputOutputModel(guiaInput, guiaOutput));
    }
end

rule "GUIA_REMISION_RELACIONADA_IO_"
when
    $inputOutput: GuiaRemisionRelacionadaInputOutputModel(
        $input : input,
        $output : output
    )
then
    $output.setSerieNumero($input.getSerieNumero());
    $output.setTipoDocumento(
            Catalog.valueOfCode(Catalog1.class, $input.getTipoDocumento()).get()
    );
end
