package rules.standard;

import org.openublpe.xmlbuilder.core.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.DocumentOutputModel;
import org.openublpe.xmlbuilder.core.models.output.common.ProveedorOutputModel;
import org.openublpe.xmlbuilder.core.models.input.common.ProveedorInputModel;

dialect "java"

rule "Proveedor"
when
    $input : ProveedorInputModel()
    $output : ProveedorOutputModel()
then
    $output.setRuc($input.getRuc());
    $output.setRazonSocial($input.getRazonSocial());
    $output.setNombreComercial($input.getNombreComercial());
    $output.setCodigoPostal($input.getCodigoPostal());
end
