package rules.standard;

import org.openublpe.xmlbuilder.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.models.output.standard.DocumentOutputModel;
import org.openublpe.xmlbuilder.models.input.standard.DetalleInputModel;
import java.util.ArrayList;
import java.math.BigDecimal;

dialect "java"

rule "Detalle"
when
    $input : DocumentInputModel(detalle != null)
    $output : DocumentOutputModel()
then
    $output.setDetalle(new ArrayList<>());
    $output.setDetalleSize($input.getDetalle().size());

    for (DetalleInputModel item : $input.getDetalle()) {
        insert(item);
    }
end
