package org.jboss.xavier.integrations.migrationanalytics.input;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * This class was automatically generated by the data modeler tool.
 */

//@javax.persistence.Entity
    @Data
    @Builder
    @AllArgsConstructor
    @NoArgsConstructor
public class InputDataModel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

/*    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "INPUTDATAMODEL_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "INPUTDATAMODEL_ID_SEQ", name = "INPUTDATAMODEL_ID_GENERATOR")*/
    private java.lang.Long id;

    @org.kie.api.definition.type.Label(value = "Customer ID")
    private java.lang.String customerId;

    @org.kie.api.definition.type.Label(value = "Source payload file name")
    private java.lang.String fileName;

    @org.kie.api.definition.type.Label(value = "Number of hosts found")
    private java.lang.Integer numberOfHosts;

    @org.kie.api.definition.type.Label(value = "Total disk space used found ")
    private java.lang.Long totalDiskSpace;

}
