package rules.note.debitNote;

import org.openublpe.xmlbuilder.models.input.general.note.AbstractNoteInputDocumentModel;
import org.openublpe.xmlbuilder.models.output.general.note.debitNote.DebitNoteOutputModel;
import org.openublpe.xmlbuilder.models.ubl.Catalog;
import org.openublpe.xmlbuilder.models.ubl.Catalog10;

dialect "java"

rule "Tipo Documento Debit Note"
when
    $input : AbstractNoteInputDocumentModel()
    $output : DebitNoteOutputModel()
then
    // Default values
    Catalog10 DEFAULT_TIPO_NOTA = Catalog10.AUMENTO_EN_EL_VALOR;

    Catalog10 tipoNota = $input.getTipoNota() != null ? Catalog.valueOfCode(Catalog10.class, $input.getTipoNota()).get() : DEFAULT_TIPO_NOTA;
    $output.setTipoNota(tipoNota);
end