package rules.standard;

import org.openublpe.xmlbuilder.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.models.input.common.ClienteInputModel;
import org.openublpe.xmlbuilder.models.output.standard.DocumentOutputModel;
import org.openublpe.xmlbuilder.models.output.common.ClienteOutputModel;
import org.openublpe.xmlbuilder.models.catalogs.Catalog;
import org.openublpe.xmlbuilder.models.catalogs.Catalog6;

dialect "java"

rule "Cliente"
when
    $input : ClienteInputModel()
    $output : ClienteOutputModel()
then
    $output.setNombre($input.getNombre());
    $output.setNumeroDocumentoIdentidad($input.getNumeroDocumentoIdentidad());

    Catalog6 tipoDocumentoIdentidad = Catalog.valueOfCode(Catalog6.class, $input.getTipoDocumentoIdentidad()).get();
    $output.setTipoDocumentoIdentidad(tipoDocumentoIdentidad);
end
