package rules.standard;

import org.openublpe.xmlbuilder.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.models.output.standard.DocumentOutputModel;

dialect "java"

rule "Serie y numero"
when
    $input : DocumentInputModel(serie != null, numero != null)
    $output : DocumentOutputModel()
then
    $output.setSerieNumero($input.getSerie().toUpperCase() + "-" + $input.getNumero());
end
