package rules.note;

import org.openublpe.xmlbuilder.models.input.general.note.AbstractNoteInputDocumentModel;
import org.openublpe.xmlbuilder.models.output.general.note.AbstractNoteOutputDocumentModel;
import org.openublpe.xmlbuilder.utils.UBLUtils;
import org.openublpe.xmlbuilder.models.ubl.Catalog6;
import org.openublpe.xmlbuilder.models.ubl.Catalog1;

dialect "java"

rule "Invoice Reference"
when
    $input : AbstractNoteInputDocumentModel(serieNumeroInvoiceReference != null)
    $output : AbstractNoteOutputDocumentModel()
then
    $output.setSerieNumeroInvoiceReference($input.getSerieNumeroInvoiceReference());
    $output.setDescripcionSustentoInvoiceReference($input.getDescripcionSustentoInvoiceReference());

    if (UBLUtils.FACTURA_SERIE_REGEX.matcher($output.getSerieNumeroInvoiceReference()).find()) {
        $output.setTipoInvoiceReference(Catalog1.FACTURA);
    } else if (UBLUtils.BOLETA_SERIE_REGEX.matcher($output.getSerieNumeroInvoiceReference()).find()) {
       $output.setTipoInvoiceReference(Catalog1.BOLETA);
    }
end