package rules.note.creditNote;

import org.openublpe.xmlbuilder.models.input.general.note.AbstractNoteInputDocumentModel;
import org.openublpe.xmlbuilder.models.output.general.note.creditNote.CreditNoteOutputModel;
import org.openublpe.xmlbuilder.models.ubl.Catalog;
import org.openublpe.xmlbuilder.models.ubl.Catalog9;

dialect "java"

rule "Tipo Documento Credit Note"
when
    $input : AbstractNoteInputDocumentModel()
    $output : CreditNoteOutputModel()
then
    // Default values
    Catalog9 DEFAULT_TIPO_NOTA = Catalog9.ANULACION_DE_LA_OPERACION;

    Catalog9 tipoNota = $input.getTipoNota() != null ? Catalog.valueOfCode(Catalog9.class, $input.getTipoNota()).get() : DEFAULT_TIPO_NOTA;
    $output.setTipoNota(tipoNota);
end