package rules.note.creditNote;

import org.openublpe.xmlbuilder.models.input.standard.note.NoteInputModel;
import org.openublpe.xmlbuilder.models.output.standard.note.creditNote.CreditNoteOutputModel;
import org.openublpe.xmlbuilder.models.catalogs.Catalog;
import org.openublpe.xmlbuilder.models.catalogs.Catalog9;

dialect "java"

rule "Tipo Documento Credit Note"
when
    $input : NoteInputModel()
    $output : CreditNoteOutputModel()
then
    // Default values
    Catalog9 DEFAULT_TIPO_NOTA = Catalog9.ANULACION_DE_LA_OPERACION;

    Catalog9 tipoNota = $input.getTipoNota() != null ? Catalog.valueOfCode(Catalog9.class, $input.getTipoNota()).get() : DEFAULT_TIPO_NOTA;
    $output.setTipoNota(tipoNota);
end
