package rules;

import org.openublpe.xmlbuilder.models.input.general.AbstractInputDocumentModel;
import org.openublpe.xmlbuilder.models.output.general.AbstractOutputDocumentModel;
import org.openublpe.xmlbuilder.models.output.ClienteOutputModel;
import org.openublpe.xmlbuilder.models.ubl.Catalog;
import org.openublpe.xmlbuilder.models.ubl.Catalog6;

dialect "java"

rule "Cliente"
when
    $input : AbstractInputDocumentModel(cliente != null)
    $output : AbstractOutputDocumentModel()
then
    ClienteOutputModel cliente = new ClienteOutputModel();
    $output.setCliente(cliente);

    cliente.setNombre($input.getCliente().getNombre());
    cliente.setNumeroDocumentoIdentidad($input.getCliente().getNumeroDocumentoIdentidad());

    Catalog6 tipoDocumentoIdentidad = Catalog.valueOfCode(Catalog6.class, $input.getCliente().getTipoDocumentoIdentidad()).get();
    cliente.setTipoDocumentoIdentidad(tipoDocumentoIdentidad);
end
