package rules;

import org.openublpe.xmlbuilder.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.models.output.standard.DocumentOutputModel;
import org.openublpe.xmlbuilder.models.output.ClienteOutputModel;
import org.openublpe.xmlbuilder.models.catalogs.Catalog;
import org.openublpe.xmlbuilder.models.catalogs.Catalog6;

dialect "java"

rule "Cliente"
when
    $input : DocumentInputModel(cliente != null)
    $output : DocumentOutputModel()
then
    ClienteOutputModel cliente = new ClienteOutputModel();
    $output.setCliente(cliente);

    cliente.setNombre($input.getCliente().getNombre());
    cliente.setNumeroDocumentoIdentidad($input.getCliente().getNumeroDocumentoIdentidad());

    Catalog6 tipoDocumentoIdentidad = Catalog.valueOfCode(Catalog6.class, $input.getCliente().getTipoDocumentoIdentidad()).get();
    cliente.setTipoDocumentoIdentidad(tipoDocumentoIdentidad);
end
