package rules;

import org.openublpe.xmlbuilder.models.input.general.AbstractInputDocumentModel;
import org.openublpe.xmlbuilder.models.output.general.AbstractOutputDocumentModel;

import function org.openublpe.xmlbuilder.utils.DateUtils.toGregorianCalendarDate;
import function org.openublpe.xmlbuilder.utils.DateUtils.toGregorianCalendarTime;

dialect "java"

rule "Fecha y hora de emision"
when
    $input : AbstractInputDocumentModel(fechaEmision != null)
    $output: AbstractOutputDocumentModel()
then
    $output.setFechaEmision(toGregorianCalendarDate($input.getFechaEmision()));
    $output.setHoraEmision(toGregorianCalendarTime($input.getFechaEmision()));
end