package rules;

import org.openublpe.xmlbuilder.models.input.general.AbstractInputDocumentModel;
import org.openublpe.xmlbuilder.models.output.general.AbstractOutputDocumentModel
import java.util.Calendar;

import function org.openublpe.xmlbuilder.utils.DateUtils.toGregorianCalendarDate;
import function org.openublpe.xmlbuilder.utils.DateUtils.toGregorianCalendarTime;

dialect "java"

rule "Fecha y Hora de emision"
when
    $input : AbstractInputDocumentModel()
    $output: AbstractOutputDocumentModel()
then
    long fechaEmision = $input.getFechaEmision() != null
        ? $input.getFechaEmision()
        : Calendar.getInstance().getTimeInMillis();
    $output.setFechaEmision(toGregorianCalendarDate(fechaEmision));
    $output.setHoraEmision(toGregorianCalendarTime(fechaEmision));
end