package rules;

import org.openublpe.xmlbuilder.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.models.output.standard.DocumentOutputModel;
import org.openublpe.xmlbuilder.models.input.FirmanteInputModel;
import org.openublpe.xmlbuilder.models.output.FirmanteOutputModel;

dialect "java"

rule "Firmante"
when
    $input : FirmanteInputModel()
    $output : FirmanteOutputModel()
then
    $output.setRuc($input.getRuc());
    $output.setRazonSocial($input.getRazonSocial());
end
