package rules;

import org.openublpe.xmlbuilder.models.input.general.AbstractInputDocumentModel;
import org.openublpe.xmlbuilder.models.output.general.AbstractOutputDocumentModel;
import org.openublpe.xmlbuilder.models.output.FirmanteOutputModel;

dialect "java"

rule "Firmante"
when
    $input : AbstractInputDocumentModel(firmante != null)
    $output : AbstractOutputDocumentModel()
then
    FirmanteOutputModel firmante = new FirmanteOutputModel();
    $output.setFirmante(firmante);

    firmante.setRuc($input.getFirmante().getRuc());
    firmante.setRazonSocial($input.getFirmante().getRazonSocial());
end