package rules;

import org.openublpe.xmlbuilder.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.models.output.standard.DocumentOutputModel;
import org.openublpe.xmlbuilder.models.output.FirmanteOutputModel;

dialect "java"

rule "Firmante"
when
    $input : DocumentInputModel(firmante != null)
    $output : DocumentOutputModel()
then
    FirmanteOutputModel firmante = new FirmanteOutputModel();
    $output.setFirmante(firmante);

    firmante.setRuc($input.getFirmante().getRuc());
    firmante.setRazonSocial($input.getFirmante().getRazonSocial());
end
