package rules;

import org.openublpe.xmlbuilder.models.input.standard.DocumentInputModel;
import org.openublpe.xmlbuilder.models.output.standard.DocumentOutputModel;

dialect "java"

// Usar PEN por defecto
rule "Moneda"
when
    $input : DocumentInputModel()
    $output : DocumentOutputModel()
then
    // Default values
    String DEFAULT_MONEDA = "PEN";

    $output.setMoneda($input.getMoneda() != null ? $input.getMoneda() : DEFAULT_MONEDA);
end
