package rules;

import org.openublpe.xmlbuilder.models.input.general.AbstractInputDocumentModel;
import org.openublpe.xmlbuilder.models.output.general.AbstractOutputDocumentModel;
import org.openublpe.xmlbuilder.models.output.ProveedorOutputModel;

dialect "java"

rule "Proveedor"
when
    $input : AbstractInputDocumentModel(proveedor != null)
    $output : AbstractOutputDocumentModel()
then
    ProveedorOutputModel proveedor = new ProveedorOutputModel();
    $output.setProveedor(proveedor);

    proveedor.setRuc($input.getProveedor().getRuc());
    proveedor.setRazonSocial($input.getProveedor().getRazonSocial());
    proveedor.setNombreComercial($input.getProveedor().getNombreComercial());
    proveedor.setCodigoPostal($input.getProveedor().getCodigoPostal());
end
