package rules.invoice;

import org.openublpe.xmlbuilder.models.input.InvoiceInputModel;
import org.openublpe.xmlbuilder.models.output.InvoiceOutputModel;
import org.openublpe.xmlbuilder.models.output.ClienteOutputModel;
import org.openublpe.xmlbuilder.models.ubl.Catalog;
import org.openublpe.xmlbuilder.models.ubl.Catalog6;

dialect "java"

rule "Cliente"
when
    $input : InvoiceInputModel(cliente != null)
    $output : InvoiceOutputModel()
then
    $output.setCliente(new ClienteOutputModel());

    $output.getCliente().setNombre($input.getCliente().getNombre());
    $output.getCliente().setNumeroDocumentoIdentidad($input.getCliente().getNumeroDocumentoIdentidad());

    $output.getCliente().setCodigoDocumentoIdentidad(
        Catalog.valueOfCode(Catalog6.class, $input.getCliente().getTipoDocumentoIdentidad())
            .map(Catalog6::getCode)
            .orElse(
                    $input.getCliente().getTipoDocumentoIdentidad()
            )
    );
end
