package rules.invoice;

import org.openublpe.xmlbuilder.models.input.InvoiceInputModel;
import org.openublpe.xmlbuilder.models.output.InvoiceOutputModel;
import org.openublpe.xmlbuilder.models.ubl.Catalog1;

dialect "java"

rule "Codigo tipo comprobante - Factura"
when
    $input : InvoiceInputModel(serie != null, serie.startsWith("F"))
    $output : InvoiceOutputModel()
then
    $output.setCodigoTipoComprobante(Catalog1.FACTURA.getCode());
end

rule "Codigo tipo comprobante - Boleta"
when
    $input : InvoiceInputModel(serie != null, serie.startsWith("B"))
    $output : InvoiceOutputModel()
then
    $output.setCodigoTipoComprobante(Catalog1.BOLETA.getCode());
end

