package rules.invoice;

import org.openublpe.xmlbuilder.models.input.AbstractInputDocumentModel;
import org.openublpe.xmlbuilder.models.input.invoice.InvoiceInputModel;
import org.openublpe.xmlbuilder.models.output.invoice.InvoiceOutputModel;
import java.math.BigDecimal;

global java.math.BigDecimal IGV;

dialect "java"

rule "Global IGV"
when
    $input : InvoiceInputModel(detalle != null)
    $output : InvoiceOutputModel()
then
    $output.setIgv(IGV);
    $output.setIgvPercent(IGV.multiply(new BigDecimal(100)));
end
