package rules.invoice;

import org.openublpe.xmlbuilder.models.input.AbstractInputDocumentModel;
import org.openublpe.xmlbuilder.models.input.invoice.InvoiceInputModel;
import org.openublpe.xmlbuilder.models.output.invoice.InvoiceOutputModel;
import org.openublpe.xmlbuilder.models.ubl.Catalog1;

dialect "java"

rule "Codigo tipo comprobante - Factura"
when
    $input : InvoiceInputModel(serie != null, serie.startsWith("F"))
    $output : InvoiceOutputModel()
then
    $output.setTipoComprobante(Catalog1.FACTURA);
end

rule "Codigo tipo comprobante - Boleta"
when
    $input : InvoiceInputModel(serie != null, serie.startsWith("B"))
    $output : InvoiceOutputModel()
then
    $output.setTipoComprobante(Catalog1.BOLETA);
end

