package org.openublpe.xmlbuilder.rules.files.standard.note.debitNote;

import org.openublpe.xmlbuilder.core.models.input.standard.note.debitNote.DebitNoteInputModel;
import org.openublpe.xmlbuilder.core.models.output.standard.note.debitNote.DebitNoteOutputModel;
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog;
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog10
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog
import org.openublpe.xmlbuilder.core.models.catalogs.Catalog10;

dialect "java"

rule "Tipo Documento Debit Note"
when
    $input : DebitNoteInputModel()
    $output : DebitNoteOutputModel()
then
    // Default values
    Catalog10 DEFAULT_TIPO_NOTA = Catalog10.AUMENTO_EN_EL_VALOR;

    Catalog10 tipoNota = $input.getTipoNota() != null ? Catalog.valueOfCode(Catalog10.class, $input.getTipoNota()).get() : DEFAULT_TIPO_NOTA;
    $output.setTipoNota(tipoNota);
end
