package rules;

import org.openublpe.xmlbuilder.models.input.AbstractInputDocumentModel;
import org.openublpe.xmlbuilder.models.output.AbstractOutputDocumentModel
import org.openublpe.xmlbuilder.models.output.FirmanteOutputModel;

dialect "java"

rule "Firmante"
when
    $input : AbstractInputDocumentModel(firmante != null)
    $output : AbstractOutputDocumentModel()
then
    $output.setFirmante(new FirmanteOutputModel());
    $output.getFirmante().setRuc($input.getFirmante().getRuc());
    $output.getFirmante().setRazonSocial($input.getFirmante().getRazonSocial());
end