package rules;

import org.openublpe.xmlbuilder.models.input.InvoiceInputModel;
import org.openublpe.xmlbuilder.models.output.InvoiceOutputModel;

import function org.openublpe.xmlbuilder.utils.DateUtils.toGregorianCalendarDate;
import function org.openublpe.xmlbuilder.utils.DateUtils.toGregorianCalendarTime;
import function org.openublpe.xmlbuilder.utils.UBLUtils.getInvoiceTypeCode;

dialect "java"

rule "Serie y numero"
when
    $input : InvoiceInputModel(serie != null, numero != null)
    $output : InvoiceOutputModel()
then
    $output.setSerieNumero($input.getSerie() + "-" + $input.getNumero());
end

rule "Fecha y hora de emision"
when
    $input : InvoiceInputModel(fechaEmision != null)
    $output: InvoiceOutputModel()
then
    $output.setFechaEmision(toGregorianCalendarDate($input.getFechaEmision()));
    $output.setHoraEmision(toGregorianCalendarTime($input.getFechaEmision()));
end

rule "Moneda"
when
    $input : InvoiceInputModel(moneda != null)
    $output : InvoiceOutputModel()
then
    $output.setMoneda($input.getMoneda());
end

rule "Codigo tipo comprobante"
when
    $input : InvoiceInputModel(serie != null)
    $output : InvoiceOutputModel()
then
    $output.setCodigoTipoComprobante(getInvoiceTypeCode($input.getSerie()));
end

