---
apiVersion: "template.openshift.io/v1"
kind: "Template"
metadata:
  labels:
    app: "xml-builder"
    group: "project-openubl"
  name: "xml-signer-knative"
objects:
  - apiVersion: "v1"
    kind: "ServiceAccount"
    metadata:
      labels:
        app: "xml-builder"
        group: "project-openubl"
      name: "xml-builder"
  - apiVersion: "serving.knative.dev/v1alpha1"
    kind: "Service"
    metadata:
      labels:
        app: "xml-builder"
        group: "project-openubl"
      name: "xml-builder"
    spec:
      runLatest:
        configuration:
          revisionTemplate:
            spec:
              container:
                image: "project-openubl/xml-builder:${XML_BUILDER_IMAGE_TAG}"
                imagePullPolicy: "IfNotPresent"
parameters:
  - name: XML_BUILDER_IMAGE_TAG
    value: "latest"
